### PR TITLE
CI testing for RDMA code paths in PoCL-D

### PR DESCRIPTION
**Pull request by jansol**

### CODE REVIEW

**Comment by jansol** [comment]
remote and rdma tests have some problems that are fixed by #1329

**Comment by franz** [comment]
The CTS / tier1 failures were caused by out-of-sync code, they should pass now.

**Comment by jansol** [comment]
Remote failure looks spurious and rdma failure is expected (maybe I should just pull these commits into the socket refactor PR instead?) The LLVM 15 failure is weird though, seems it's missing the AMDSDK dependency? Definitely looks unrelated to this PR though.

**Comment by pjaaskel** [comment]
@jansol yep please pull the CI to the other PR. The AMD SDK test suite problem is unrelated.

**Pull request closed without merging**
