### PR TITLE
Avoid inheritance from std::vector in ParallelRegion class.

### PR DESCRIPTION
**Pull request by rusyaev-roman**
Use composition instead of inheritance.

### CODE REVIEW

**Comment by pjaaskel** [comment]
Did you try running tier1 tests with this? Pulling this in seems to cause a segfault in a PyOpenCL test.

**Comment by rusyaev-roman** [comment]
Oh, sorry. I'll double check this

**Review by pjaaskel — CHANGES_REQUESTED** [review]
Test issue (might be transitional).

**Comment by pjaaskel** [comment]
Hi, can you update this PR? I'll then retest and pull it in if my local test envs pass. Thanks!

**Comment by rusyaev-roman** [comment]
> Did you try running tier1 tests with this? Pulling this in seems to cause a segfault in a PyOpenCL test.

Could you check it again? I've run it manually and it passed successfully.

**Pull request merged**
