### PR TITLE
Fix excessive retaining of mem objects

### LINKED ISSUE #1108: PoCL memory leaks since cl_khr_command_buffer merge
Discovered while trying to run OpenCL-CTS on a weaker machine. Some of the CTS tests cause PoCL to eat >10 gigabytes of memory.

After reverting commit 5ddd3c63dbeff3752d3d13aa8f486eafac4e24de and commit 1068c530d889dd0238371ae927ea898cae588366 everything is properly cleaned up:
```
export POCL_ENABLE_UNINIT=1
POCL_DEBUG=all ./examples/example0/example0
.....
[2022-10-21 07:59:02.757466505]POCL: in fn void pocl_llvm_release_context(cl_context) at line 418:
  |      LLVM |  releasing LLVM context
[2022-10-21 07:59:02.858114771]POCL: in fn pocl_check_uninit_devices at line 140:
  | REFCOUNTS |  Zero contexts left, calling pocl_uninit_devices
[2022-10-21 07:59:02.858149971]POCL: in fn pocl_uninit_devices at line 357:
  |   GENERAL |  UNINIT all devices
```

... and `conformance_integer_ops_micro_3` requires about 1.6GB of memory to run. Without those two reverts, 
`conformance_integer_ops_micro_3` eats 10+ gigabytes and the example0 log shows:

```
[2022-10-21 08:14:22.537842048]POCL: in fn POclReleaseContext at line 48:
  | REFCOUNTS |  Release Context 2 (0x55d03f2b3820), Refcount: 4
[2022-10-21 08:14:22.637983686]POCL: in fn pocl_check_uninit_devices at line 148:
  |     ERROR |  Contexts remaining!! 
```
... there are no `Free Event N` messages in the log, so i assume events are not freed at all. @jansol can you take a look ?

### PR DESCRIPTION
**Pull request by jansol**
Fixes #1108

It seems events were just a red herring, the real culprit of the memory leak appears to have been that required mem objects are stored in two different places depending on whether the command is recorded to a command buffer or enqueued immediately. The latter store the list of mem objects in the event and release them in `pocl_update_event_finished` while the former store the list in the command node directly and release the mem objects only when the command is freed along with the command buffer it was recorded to.

Can you confirm that this patch fixes the problem @franz ? If it does then it's probably best to take some time to unify the mem object handling between the two code paths.

### CODE REVIEW

**Comment by franz** [comment]
Thanks, i'll take a look

**Comment by franz** [comment]
That indeed does fix the memleaks for *almost* all cases. The command buffer tests still fail with ASAN build:

```
93% tests passed, 2 tests failed out of 29

The following tests FAILED:
	120 - runtime/test_command_buffer (Failed)
	121 - runtime/test_command_buffer_images (Failed)
```

after adding `clUnloadCompiler` to those two tests, ASAN shows the memleaks to be events + buffers + kernel args(?) :

```
==208351==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1076976 byte(s) in 4986 object(s) allocated from:
    #0 0x7f977b731a06 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x7f977b47d289 in pocl_mem_manager_new_event /home/michal/0/source/pocl/lib/CL/pocl_mem_management.c:33
    #2 0x7f977b4597b2 in pocl_create_event /home/michal/0/source/pocl/lib/CL/pocl_util.c:498
    #3 0x7f977b459d28 in pocl_create_command_struct /home/michal/0/source/pocl/lib/CL/pocl_util.c:638
    #4 0x7f977b45dd9b in pocl_create_command_full /home/michal/0/source/pocl/lib/CL/pocl_util.c:1023
    #5 0x7f977b45e2df in pocl_create_command /home/michal/0/source/pocl/lib/CL/pocl_util.c:1068
    #6 0x7f977b49af4d in POclEnqueueCommandBufferKHR /home/michal/0/source/pocl/lib/CL/clEnqueueCommandBufferKHR.c:183
    #7 0x55aa7c1bd297 in main /home/michal/0/source/pocl/tests/runtime/test_command_buffer.c:211
    #8 0x7f977b1a0082 in __libc_start_main ../csu/libc-start.c:308

Direct leak of 424 byte(s) in 1 object(s) allocated from:
    #0 0x7f977b731a06 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x7f977b3e51a4 in pocl_create_memobject /home/michal/0/source/pocl/lib/CL/clCreateBuffer.c:110
    #2 0x7f977b3e6456 in POclCreateBuffer /home/michal/0/source/pocl/lib/CL/clCreateBuffer.c:246
    #3 0x55aa7c1bc571 in main /home/michal/0/source/pocl/tests/runtime/test_command_buffer.c:135
    #4 0x7f977b1a0082 in __libc_start_main ../csu/libc-start.c:308

Direct leak of 424 byte(s) in 1 object(s) allocated from:
    #0 0x7f977b731a06 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x7f977b3e51a4 in pocl_create_memobject /home/michal/0/source/pocl/lib/CL/clCreateBuffer.c:110
    #2 0x7f977b3e6456 in POclCreateBuffer /home/michal/0/source/pocl/lib/CL/clCreateBuffer.c:246
    #3 0x55aa7c1bc487 in main /home/michal/0/source/pocl/tests/runtime/test_command_buffer.c:129
    #4 0x7f977b1a0082 in __libc_start_main ../csu/libc-start.c:308

Direct leak of 424 byte(s) in 1 object(s) allocated from:
    #0 0x7f977b731a06 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x7f977b3e51a4 in pocl_create_memobject /home/michal/0/source/pocl/lib/CL/clCreateBuffer.c:110
    #2 0x7f977b3e6456 in POclCreateBuffer /home/michal/0/source/pocl/lib/CL/clCreateBuffer.c:246
    #3 0x55aa7c1bc4fc in main /home/michal/0/source/pocl/tests/runtime/test_command_buffer.c:132
    #4 0x7f977b1a0082 in __libc_start_main ../csu/libc-start.c:308

Direct leak of 384 byte(s) in 48 object(s) allocated from:
    #0 0x7f977b7326e5 in __interceptor_posix_memalign ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:217
    #1 0x7f977b4514b4 in pocl_memalign_alloc /home/michal/0/source/pocl/lib/CL/pocl_util.c:299
    #2 0x7f977b451d9a in pocl_aligned_malloc /home/michal/0/source/pocl/lib/CL/pocl_util.c:331
    #3 0x7f977b478ee5 in pocl_kernel_copy_args /home/michal/0/source/pocl/lib/CL/pocl_ndrange_kernel.c:288
    #4 0x7f977b47a7cd in pocl_ndrange_kernel_common /home/michal/0/source/pocl/lib/CL/pocl_ndrange_kernel.c:399
    #5 0x7f977b497a04 in POclCommandNDRangeKernelKHR /home/michal/0/source/pocl/lib/CL/clCommandNDRangeKernelKHR.c:45
    #6 0x55aa7c1bcb65 in main /home/michal/0/source/pocl/tests/runtime/test_command_buffer.c:159
    #7 0x7f977b1a0082 in __libc_start_main ../csu/libc-start.c:308
```

**Comment by jansol** [comment]
That should take care of those. Something weird is going on though, ASAN complains about a double free with the syncpoint events now. However if I remove the clReleaseEvent it tells me those same events got leaked.

**Comment by jansol** [comment]
Now ASAN is finally happy.

**Comment by pjaaskel** [comment]
@franz can you check that this fixed the conformance test leak?

**Pull request merged**
