### PR TITLE
Fix runtime error 'undefined symbol: pocl_ignore_sigfpe_for_thread' on aarch64

### PR DESCRIPTION
**Pull request by jandrovins**
Solves #1196

### CODE REVIEW

**Comment by buni-rock** [comment]
As you have already spotted, the declaration of the  **pocl_ignore_sigfpe_for_thread** is located under the  **#ifdef x86_64**. With your pull request, you have done the same for the call of the function, but the definition of this function is still available in the header file. I have suggested to guard the definition of the function in the header file so that **definition/declaration/function calls** are consistently guarded.

**Comment by pjaaskel** [comment]
Thanks. Can you add a mention of this fix to CHANGES, it might interest others trying to use PoCL in ARM?

**Comment by franz** [comment]
@pjaaskel  i think this should not be in CHANGES - this bug was introduced in March commit 94546bc787371a78a855c2f01187cf, so it's not a change from previous release. Pretty sure PoCL 3.1 release works (reasonably) on ARM64, [it was tested](https://github.com/pocl/pocl/wiki/Release-testing-of-pocl-3.1).

**Comment by jandrovins** [comment]
Added guard to https://github.com/pocl/pocl/blob/c141fb77ab7e8e219848edcc5576be2bc2ba3213/lib/CL/pocl_util.h#L63 as suggested by @buni-rock

**Pull request merged**
