### PR TITLE
cuda: refresh running on Jetson nano

### PR DESCRIPTION
**Pull request by trixirt**
On Jetson nano with jetpack 4.6 / Cuda 10.2
gcc/clang builtin is __aarch64__ instead of __arm__

In pocl_cuda_alloc_mem_obj(), the second parameter changed its
identifier from mem_obj to mem, so the use in the arm ifdef had to change.

In pocl_cuda_finalize_command() the event structure changed so its use
needed to change.  meta->num_args was wrong it should have been
kernel->meta->num_args.

Fixes most ctest failures.

Signed-off-by: Tom Rix <trix@redhat.com>

### CODE REVIEW

**Comment by pjaaskel** [comment]
Does it look ok to pull @jrprice ?

**Review by jrprice — APPROVED** [review]
LGTM!

**Comment by isuruf** [comment]
Can we please merge #890 instead of this?

**Comment by pjaaskel** [comment]
@isuruf I merged #890. Is there something more in this PR that needs to be pulled in @trixirt?

**Comment by trixirt** [comment]
not sure as the target looks like xavier and i have have nano
Since its' merged, i'll give it a try .

**Pull request closed without merging**
