### PR TITLE
Enable pocl relocation

### PR DESCRIPTION
**Pull request by isuruf**
With ENABLE_POCL_RELOCATION option, no hard coded paths are used in libpocl.so
making it possible to relocate pocl.

### CODE REVIEW

**Comment by pjaaskel** [comment]
Is there a reason this could not be enabled by default and unconditionally?

**Comment by franz** [comment]
Is it copying the Clang opencl-c.h header to pocl's installation because you're also relocating Clang ?

**Comment by isuruf** [comment]
> Is there a reason this could not be enabled by default and unconditionally?

There was an extra dependency on dl, but I guess that's fine since pocl requires ltdl. (Btw, what was the reason to use ltdl instead of simply dl?)

> Is it copying the Clang opencl-c.h header to pocl's installation because you're also relocating Clang ?

I'm building clang and llvm statically, so there's no need to have a clang when relocating.

Right now if I relocate pocl with hwloc and ltdl alongside, I only need `ld` and `libm.so` (a symlink to libm.so.6) in the user system except for glibc and other system libraries.

We can avoid the need for `libm.so` by removing `-lm` from `HOST_LD_FLAGS` as pocl is linked to `libm.so.6` and there's no need for the shared libraries created by pocl to explicitly link to `libm.so`. What do you think?

I can also remove the need for `ld` by linking in `lld` as a library with a few lines. (Maybe with a `LINK_WITH_LLD_LIBRARY` option). What do you think?

**Comment by franz** [comment]
> Btw, what was the reason to use ltdl

The reason (i'm guessing here) probably was because pocl originally used GNU autotools. But also see last paragraph..

> We can avoid the need for libm.so by removing -lm from HOST_LD_FLAGS as pocl is linked to libm.so.6 

i think we can do that, as long as we ensure libpocl.so itself is linked to libm.

> I can also remove the need for ld by linking in lld as a library with a few lines

I think introducing lld will not be necessary. One of the things we've agreed on with Pekka is to remove support for LLVM <= 5.0 (Ubuntu 18.04 LTS has 6.0 so we want to keep that), so the entire code that uses "ld" with LLVM < 5.0 will be gone, and we will simply link using Clang (unless there's good reason to do otherwise).

BTW @isuruf i have a fair amount of patches to make the pocl runtime (not the drivers) more flexible and portable, but i haven't finished cleaning them up yet. If you have some bigger PR incoming then maybe we should talk in private and/or pocl-devel to avoid duplicating work.

**Comment by pjaaskel** [comment]
ltdl was chosen by @csanchezdll who started the pocl code base originally. The reason was likely, in addition to using autotools, also because of hopes of improved portability to his MacOS laptop which he liked to use back then, but cannot remember for sure.

**Comment by isuruf** [comment]
> I think introducing lld will not be necessary. One of the things we've agreed on with Pekka is to remove support for LLVM <= 5.0 (Ubuntu 18.04 LTS has 6.0 so we want to keep that), so the entire code that uses "ld" with LLVM < 5.0 will be gone, and we will simply link using Clang (unless there's good reason to do otherwise).

Even if the linking was done using clang, a linker is needed as clang would call a linker. My need was to avoid requiring a linker on a user's system.

For example, unpacking https://github.com/isuruf/isuruf.github.io/releases/download/v1.0/pocl-1.3-x86_64-linux-gnu.tar.gz and adding a `.icd` to point to it would work on any glibc based system linux system newer than centos5. Only dependencies will be the following libraries which should be available.

```
        linux-vdso.so.1 =>  (0x00007ffe79dd9000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f888c86f000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f888c66b000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f888c44f000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f888c1cc000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f888becc000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f888bcbe000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f888b965000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f88904d3000)
```

> If you have some bigger PR incoming then maybe we should talk in private and/or pocl-devel to avoid duplicating work.

I might send a PR to avoid ltdl, but that's it.

**Comment by isuruf** [comment]
@pjaaskel, @franz, let me know what you think about this and I'll be happy to make any changes.

**Comment by franz** [comment]
> Even if the linking was done using clang, a linker is needed as clang would call a linker

Hmm ok, i haven't looked at `pocl_invoke_clang()` for a while. But it seems to me that instead of having two ways to invoke the linker, we should aim for a single one. @pjaaskel what do you think

> I might send a PR to avoid ltdl, but that's it.

There's no need for that. But it'd be useful if you could add a Travis-CI config for this feature.

**Comment by pjaaskel** [comment]
> But it seems to me that instead of having two ways to invoke the linker, we should aim for a single one. 

Yes, I think the clang Driver/Toolchain API could be delegated to when invoking the linker. The toolchain information is there, why not use it? 

Only thing that I have to ask/figure about this PR is that is it necessary to make this feature optional? Does it break a use case if it was always on?

**Comment by isuruf** [comment]
> Yes, I think the clang Driver/Toolchain API could be delegated to when invoking the linker. The toolchain information is there, why not use it?

There might not be a linker in a user's system. In that case, I'd like to build pocl with lld linked in, so that the user doesn't need to install a linker.

> Only thing that I have to ask/figure about this PR is that is it necessary to make this feature optional? Does it break a use case if it was always on?

No, I'll remove the cmake option.

**Comment by pjaaskel** [comment]
Please add an entry to CHANGE that briefly describes this useful feature.

**Comment by pjaaskel** [comment]
This now looks good to me.

BTW, it seems you got OSX working. Could you update README.OSX, or even better, add the updated information to the user manual?

**Comment by isuruf** [comment]
>  add the updated information to the user manual?

Which file should they go into?

Btw, I've got a docker file that builds pocl and dependencies on CentOS 5 x86_64. If you are interested I can put it in this repo so that when you release a new version, you can provide a binary archive that any user (with a GLIBC 2.5 or newer) can use just by unpacking and creating a icd file to point to it.

**Comment by pjaaskel** [comment]
> Which file should they go into?

I think next to the android usage in [using.rst](http://portablecl.org/docs/html/using.html#using-pocl-on-android) is a good spot.

> Btw, I've got a docker file that builds pocl and dependencies on CentOS 5 x86_64. If you are interested I can put it in this repo so that when you release a new version, you can provide a binary archive that any user (with a GLIBC 2.5 or newer) can use just by unpacking and creating a icd file to point to it.

This should be useful to the community. Also please add documentation for that then.

Thanks for your contributions so far!

**Comment by isuruf** [comment]
I'll send separate PRs for the two items mentioned above.

**Comment by franz** [comment]
I've added a few fixes on top of this PR in #732.

**Pull request closed without merging**
