### PR TITLE
swap calloc args in enqueueMigrateMemObjects

### PR DESCRIPTION
**Pull request by RABijl**
small fix to prevent potential padding from messing things up

### CODE REVIEW

**Comment by pjaaskel** [comment]
I don't understand what swapping the arguments changes here, pls explain.

**Comment by RABijl** [comment]
from the description of calloc: 
```
extern void *calloc(size_t __nmemb, size_t __size)
Allocate NMEMB elements of SIZE bytes each, all initialized to 0
```
this is just to prevent bugs with alignment

**Comment by RABijl** [comment]
fair point, and in theory the end result should be the same. However, we don't know what different implementations of stdlib will do with the information we are providing (i.e. nmemb and size).

**Comment by pjaaskel** [comment]
Right, so what's the point of the patch then? If you want to enforce alignment, better use an API that enforces it instead.

**Pull request closed without merging**
