### PR TITLE
Implement clEnqueueFillBuffer for TCE

### PR DESCRIPTION
**Pull request by TopiLeppanen**

### CODE REVIEW

**Comment by pjaaskel** [comment]
Is there a test that could be enabled for TCE with this commit?

**Comment by TopiLeppanen** [comment]
> Is there a test that could be enabled for TCE with this commit?

It does enable test-memfill for TCE

> This should also be included in the AlmaIF implementation of TCE

Oh right, I'll get that done as well

**Comment by pjaaskel** [comment]
> > Is there a test that could be enabled for TCE with this commit?
> 
> It does enable test-fill-buffer for TCE

Can you add the respective tags so it gets run in run_*_tests?

**Comment by TopiLeppanen** [comment]
> > > Is there a test that could be enabled for TCE with this commit?
> > 
> > 
> > It does enable test-fill-buffer for TCE
> 
> Can you add the respective tags so it gets run in run_*_tests?

It does now get run in run_tta_tests. This adds the label 'tce' to the fill-buffer test, and the run_tta_tests runs tests with the label 'tce'.
Do you mean something else than that?

**Comment by pjaaskel** [comment]
> It does now get run in run_tta_tests. This adds the label 'tce' to the fill-buffer test, and the run_tta_tests runs tests with the label 'tce'. Do you mean something else than that?

AlmaIF, when it works.

**Comment by TopiLeppanen** [comment]
Ok I did do that in #1137

**Pull request merged**
