### PR TITLE
Updated included headers to OpenCL 3.0 + implemented clGetDeviceInfo atomic memory consistency queries

### PR DESCRIPTION
**Pull request by Vinsteri**
This is part of implementing OpenCL 3.0 support for PoCL. This pull request includes update to included OpenCL headers and implementation of two new queries in clGetDeviceInfo.

- Updated included OpenCL 3.0 headers to the latest release version (v2020.06.16) from https://github.com/KhronosGroup/OpenCL-Headers  with latest OpenCL api c++ bindings (v2.0.12) from https://github.com/KhronosGroup/OpenCL-CLHPP (v2.0.12).

- Changed TARGET_OPENCL_VERSION to 300. New headers require this to enable OpenCL 3.0 features.

- Changed POCL_CL_VERSION to 3.0. As far as I understood this is only a cosmetic change.

- Implemented new clGetDeviceInfo queries CL_DEVICE_ATOMIC_MEMORY_CAPABILITIES and CL_DEVICE_ATOMIC_FENCE_CAPABILITIES. 

Devices report atomic memory and fence capabilities through new device struct members atomic_memory_capability and atomic_fence_capability. OpenCL mandates support minimum capability for devices which is set in devices/common.c. For now only devices basic and pthread overwrite this to report full memory consistency model* (*except CL_DEVICE_ATOMIC_SCOPE_ALL_DEVICES)

This implementation is very minimal since other devices (cuda, hsa and tce) only report the minimum mandated memory consistency model. This is because I couldn't really say what level of support should be reported for these devices. 

For overview of atomic and fence operations  see https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#_overview_of_atomic_and_fence_operations 
On backwards compatibility https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#_memory_consistency_model

- extended coverage of test_clGetDeviceInfo.c to check that at least the minimum mandated support is reported for the new queries.

make check_tier1 passes

### CODE REVIEW

**Comment by pjaaskel** [comment]
Can you rebase this branch so it has one commit for the header update and one for your new query? Also please add yourself to CREDITS and update CHANGES with this new features.

**Comment by pjaaskel** [comment]
Building the CUDA driver fails with this pulled in:
```
/home/visit0r/src/pocl/lib/CL/devices/cuda/pocl-cuda.c:169:10: error: ‘CL_DEVICE_ATTRIBUTE_ASYNC_ENGINE_COUNT_NV’ undeclared$
     case CL_DEVICE_ATTRIBUTE_ASYNC_ENGINE_COUNT_NV:                                                                         
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                          
          CU_DEVICE_ATTRIBUTE_ASYNC_ENGINE_COUNT                                                                             
/home/visit0r/src/pocl/lib/CL/devices/cuda/pocl-cuda.c:169:10: note: each undeclared identifier is reported only once for ea$
/home/visit0r/src/pocl/lib/CL/devices/cuda/pocl-cuda.c:173:10: error: ‘CL_DEVICE_PCI_BUS_ID_NV’ undeclared (first use in thi$
     case CL_DEVICE_PCI_BUS_ID_NV:
          ^~~~~~~~~~~~~~~~~~~~~~~
          CL_DEVICE_PCIE_ID_AMD
/home/visit0r/src/pocl/lib/CL/devices/cuda/pocl-cuda.c:177:10: error: ‘CL_DEVICE_PCI_SLOT_ID_NV’ undeclared (first use in th$
     case CL_DEVICE_PCI_SLOT_ID_NV:
          ^~~~~~~~~~~~~~~~~~~~~~~~
          CL_DEVICE_PCI_BUS_ID_NV
/home/visit0r/src/pocl/lib/CL/devices/cuda/pocl-cuda.c:181:10: error: ‘CL_DEVICE_PCI_DOMAIN_ID_NV’ undeclared (first use in $
     case CL_DEVICE_PCI_DOMAIN_ID_NV:                                                                                        
          ^~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                         
          CL_DEVICE_PCI_SLOT_ID_NV 
```
Some ext header change perhaps?

**Comment by Vinsteri** [comment]
I had overlooked the possibility that the headers would have changes outside the OpenCL specification. This issue arises from changes made in #910, where some cuda specific device queries were added to the headers. I'll see if I can forward these changes to the new headers. I'll also check if there are other similar cases.

**Comment by franz** [comment]
LGTM, only a minor nitpick: can you please git-rebase the branch on master, in the rebase set the `Implemented clGetDeviceInfo atomic memory and fence queries` commit to editing, and run  `tools/scripts/format-last-commit.sh` on it (it's a short script that formats the code according to PoCL guidelines)

**Pull request merged**
