### PR TITLE
More travis-ci testing

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
Here's a job in my account, https://travis-ci.org/isuruf/pocl/builds/381242588

**Comment by franz** [comment]
OK, found a few issues (sort of). 

1) the Docker builds do not run the tests (they only call `docker build` not `docker run`) and they don't install pocl before running tests (which is my fault, missing `ninja install` in some Dockerfiles)

2) Just FYI, the Conda builds are using Ubuntu 14.04 which has known issues with pocl - see #590. This problem pops up somewhat randomly, and seems to be a bug in GCC - https://bugs.launchpad.net/ubuntu/+source/gcc-defaults/+bug/1228201 ...so you may or may not run into this.

**Comment by franz** [comment]
OK, looks good. Running in Travis now.

**Comment by franz** [comment]
https://travis-ci.org/franz/pocl/builds/382514677 one of the Docker jobs seems to be stuck in apt-get for some reason, but i'm guessing it's a build environment problem, not a pocl problem. But the other Docker job runs the tests now, so LGTM.

**Comment by isuruf** [comment]
Looks like that issue was resolved, but there are test failures in ppc64le. Shall I mark the job as "allowed failure" ?

**Comment by franz** [comment]
@isuruf  well, how much do you care about ppc64 ? the two tests failing are not really suprising, since the whole passing-struct-as-kernel-args is not well defined in OpenCL. We can if-not-ppc them in CMake.

**Comment by isuruf** [comment]
> how much do you care about ppc64 ?

I don't. I reverted that commit.

**Pull request merged**
