### PR TITLE
Fixing use or removed APIs

### PR DESCRIPTION
**Pull request by Michoumichmich**
Fixes https://github.com/pocl/pocl/issues/990 to build with LLVM 14

### CODE REVIEW

**Comment by pjaaskel** [comment]
Did you test to build this with older LLVMs? How old?

**Comment by Michoumichmich** [comment]
> Did you test to build this with older LLVMs? How old?

Hello, It's my first time contributing here, I will check on LLVM 13, should I try older versions?

**Comment by pjaaskel** [comment]
Hi - and always glad to see new contributors! In principle yes, you should test at least the latest two LLVMs, but if you wrap your change in the LLVM version check macros (a newer than 13 macro here) with the old one as a fallback it should be safe. I personally currently locally test before pushing PRs with LLVMs down to 6.

**Comment by franz** [comment]
fails on buildbots with LLVM 7:

```
/worker/llvm_70_pthread/source/lib/llvmopencl/OptimizeWorkItemFuncCalls.cc:133:27: error: ‘class llvm::CallInst’ has no member named ‘arg_size’
  133 |         assert(MovedCall->arg_size() == CallInst->arg_size());
      |                           ^~~~~~~~
/worker/llvm_70_pthread/source/lib/llvmopencl/OptimizeWorkItemFuncCalls.cc:133:51: error: ‘class llvm::CallInst’ has no member named ‘arg_size’
  133 |         assert(MovedCall->arg_size() == CallInst->arg_size());
      |                                                   ^~~~~~~~
/worker/llvm_70_pthread/source/lib/llvmopencl/OptimizeWorkItemFuncCalls.cc:136:45: error: ‘class llvm::CallInst’ has no member named ‘arg_size’
  136 |         for (unsigned I = 0; I < MovedCall->arg_size(); ++I) {
      |                                             ^~~~~~~~
```
LLVM 8 to 13 work fine.

**Comment by Michoumichmich** [comment]
Okay, I'll add a pragma for this too. 
I have the two spirv examples, `example0` and `example1` that fails on LLVM 14 with `spirv file not found` but works on other version, but I don't think that it's related to these modifications.

**Comment by Michoumichmich** [comment]
Should I use `LLVM_OLDER_THAN_...` ?

**Comment by pjaaskel** [comment]
> Should I use `LLVM_OLDER_THAN_...` ?

Yep.

**Comment by Michoumichmich** [comment]
> > Should I use `LLVM_OLDER_THAN_...` ?
> 
>

That's fixed!

**Comment by pjaaskel** [comment]
Can you add yourself to the end of CREDITS too?

**Comment by Michoumichmich** [comment]
> Can you add yourself to the end of CREDITS too?

Done :)

**Pull request merged**
