### PR TITLE
Update Vecmathlib

### PR DESCRIPTION
**Pull request by eschnett**
Use AVX2 intrinsics (Haswell instructions) if available.

This should (but I didn't measure it) improve performance on some new Intel CPUs.

This might break the build on some platforms where I can't test. I would not apply this just before a release.

### CODE REVIEW

**Comment by pjaaskel** [comment]
Yep, seems so major that better postpone merging it until the 0.13 start.

**Comment by pjaaskel** [comment]
@franz can you pls check&test&push it?

**Comment by eschnett** [comment]
I have two AVX2 bug fixes in the main vecmathlib source tree that should be included as well. I will update my pull request shortly.

**Comment by franz** [comment]
OK, i'll take a look when you update.

**Comment by eschnett** [comment]
I updated.

**Pull request merged**
