### PR TITLE
Ask device for kernellib name

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by pjaaskel** [comment]
Hi @isuruf, we are likely branching 5.0 quite soon. Are you planning to get this in?

**Comment by isuruf** [comment]
Yes, I can start working on this again. When do you plan to branch to 5.0?

**Comment by pjaaskel** [comment]
Hopefully early next week. But there's still a bunch of PR to pull in.

**Comment by franz** [comment]
Hi @isuruf you could also add a new callback into `device->ops` struct for getting the kernellib name, if you think it would simplify the code more.

**Review by pjaaskel — APPROVED** [review]
Thanks for the cleanup, looks much better now. @franz are you happy with pulling this in?

**Comment by pjaaskel** [comment]
Looking at this again, did you consider the above suggestion from @franz  to add a new device function that would generate the kernel lib name? Might be even cleaner than this solution.

**Comment by isuruf** [comment]
> Looking at this again, did you consider the above suggestion from @franz to add a new device function that would generate the kernel lib name? Might be even cleaner than this solution.

Sorry. Let's create an issue and track this.

**Pull request merged**
